# Generated by Django 6.0 on 2026-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_settlement_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
